FROM openjdk:17-oracle

ENV JVM_OPTIONS="--add-opens java.base/java.lang=ALL-UNNAMED"

COPY staging/*.jar /backend.jar

EXPOSE 9000 9001

ENTRYPOINT java --add-opens java.base/java.lang=ALL-UNNAMED -jar -Dspring.profiles.active=DEV /backend.jar
