version: '3.2'

# Create appication and development services
services:

### APPLICATION SERVICES ###

  ## Frontend service
 ## Open: http://localhost/
 frontend-self-contained:
   container_name: frontend-self-contained
   build: ./frontend-self-contained
   ports:
     - "8484:8484"

  ## Backend service
  ## Open: http://localhost:9000
 backend-self-contained:
   container_name: backend-self-contained
   build: ./backend-self-contained
   ports:
     - "9000:9000"
   depends_on:
     - db

  ## The database starts automatically with Docker
 ## The ./db/Dockerfile creates the databases and users
 db:
   container_name: db
   build: ./db
   ports:
     - "5432:5432"
   restart: always